name: noaa-ai
channels:
  - conda-forge
  - nodefaults
platforms:
  - linux-64
  - osx-64
dependencies:
  - python ~=3.11.7

  - pre-commit
  - pystac
  - rasterio
  - shapely

  # jupyter environment
  - jupyter
