name: noaa-ai
channels:
  - conda-forge
  - nodefaults
platforms:
  - linux-64
  - osx-64
dependencies:
  - python ~=3.11.7

  - click
  - earthpy
  - netcdf4
  - numpy
  - pandas
  - packaging
  - pre-commit
  - pystac
  - rasterio
  - shapely
  - pathlib
  - xarray
  - xstac

  # jupyter environment
  - jupyter
